version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ebe_postgres
    restart: always
    environment:
      POSTGRES_USER: ebe_user
      POSTGRES_PASSWORD: ebe_password
      POSTGRES_DB: ebe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ebe_api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ebe_user
      DB_PASSWORD: ebe_password
      DB_NAME: ebe_db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
